import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderBar from './shared-components/header-bar'
import FooterBar from './shared-components/footer-bar'
import './layout.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root">
          <main className='page-container'>
            <HeaderBar />
            <div className="children-container">
              {children}
            </div>
            <FooterBar />
          </main>
        </div>
      </body>
    </html>
  )
}
